name: "Test coverage comment"
description: "Leave a test coverage comment on pull request."
author: "pooi (Taewoo You)"

inputs:
  github-token:
    description: "secrets.GITHUB_TOKEN value"
    required: true
  xml-test-report-path:
    description: 'The test report paths (xml, split by comma(,))'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: python -m pip install -r "$GITHUB_ACTION_PATH/requirements.txt"
      shell: bash

    - name: Extract test coverage
      shell: bash
      run: |
        python "$GITHUB_ACTION_PATH/main.py" "${{ inputs.xml-test-report-path }}" ${{ inputs.github-token }} ${{ github.api_url }} ${{ github.repository }} ${{ github.ref }} ${{ github.event.pull_request.url }}
